### ISSUE TITLE
Check if terraform modules are up-to-date using modules.dnx.one API

### ISSUE THREAD

**Issue by arthurbdiniz** [DNXLabs/one-cli#58] opened 2020-06-26 01:36 UTC
The idea for this feature is to check the version of terraforming modules been used in the current project and compare it with modules.dnx.one/api.json endpoint. 
In case any module is not in the latest version warn the CLI used about it.

**Comment by brunodasilvalenga** [comment] 2020-06-26 01:47
Duplicate of #59

**Closed as completed** 2020-07-02 23:08 UTC
Labels: feature
